### ISSUE TITLE
Composer installation issues

### ISSUE THREAD

**Issue by Lewiscowles1986** [magento/magento2-community-edition#15] opened 2015-11-22 23:16 UTC
So the following fails...

```shell
mkdir -p /var/www/magento2
cd /var/www/magento2
git clone https://github.com/magento/magento2-community-edition .
git checkout 2.0.0
composer config --global http-basic.repo.magento.com 0e6cd217fe282abe72926b205a9419c2 04867ce7191d8f32b45e4d7a5f4d235f
composer install --no-progress --no-dev
```

**Error**

![image](https://cloud.githubusercontent.com/assets/2605791/11326935/d17c854a-916e-11e5-9499-147f14c49796.png)

Not sure why this is happening, if I am not supposed to clone this repo, then please add a note on the front of the repo, it was bad enough having to add credentials that I did not have to add in the beta

**Comment by mttjohnson** [comment] 2015-11-23 17:02
I ran into the same error with the `NonComposerComponentRegistration.php` file when running a composer install.
```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition ./
```

my situation is a has some unique aspects because I was able to use the exact same command on a different environment and it worked fine, which leads me to believe there may be some environment related difference that could be causing this.

When it runs, it pulls in all the required files into the vendor folder, but never copies the magento2-base files over to the project root, which is why I expect it's complaining about the `app/etc/NonComposerComponentRegistration.php` not existing.

I'm wondering if something is off with the order that things get executed, and some module registration is trying to execute before the magento2-base package gets it's files copied over.

Running from my Mac OS X 10.10 it would fail, but on a virtual machine running CentOS it worked fine. I verified that all the PHP extensions that exist on my CentOS VM are also installed on my Mac OS host.

Mac: 
```
PHP 5.6.15 (cli) (built: Oct 31 2015 07:39:24) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with the ionCube PHP Loader v5.0.17, Copyright (c) 2002-2015, by ionCube Ltd.
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```

CentOS:
```
PHP 5.6.14 (cli) (built: Sep 30 2015 14:07:43) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.0.18, Copyright (c) 2002-2015, by ionCube Ltd.
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```

**Comment by mttjohnson** [comment] 2015-11-23 17:09
I failed to mention that I had run a composer install from my host (Mac OS X) of Magento last Tuesday night after the 2.0 GA and it ran fine from my host, but since Friday when I found out about the new developer secure keys that I could use to authenticate to the repo.magento.com it seems to not work correctly from my host (Mac OS X) any longer. Not sure what could have changed, but that's what I noticed.

**Comment by xcomSteveJohnson** [comment] 2015-11-23 17:19
@mttjohnson Just a guess but did you update auth.json with the keys?

**Comment by mttjohnson** [comment] 2015-11-23 17:46
@xcomSteveJohnson I have tried multiple combinations of authenticating both interactive, and with a composer home auth.json file. I have also run `composer clear-cache` just for fun to make sure it's authenticating and not just pulling cached copies. I have also included credentials in the repo address `composer create-project --repository-url=https://${MAGENTO_PUB_KEY}:${MAGENTO_PRIV_KEY}@repo.magento.com/ magento/project-community-edition ./`. The authenticating is not an issue, and I have verified that it authenticates successfully. All variations are resulting in the same error on my Mac, but not the CentOS VM.

**Comment by mttjohnson** [comment] 2015-11-23 18:02
On my Mac, if I separate things and get the meta package with composer --no-install it downloads the meta package just fine. It is during the `composer install` where it hits the error.

```
mattjohnson $ composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition ./ --no-install
Installing magento/project-community-edition (2.0.0)
  - Installing magento/project-community-edition (2.0.0)
    Loading from cache

Created project in ./
mattjohnson $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing magento/magento-composer-installer (0.1.5)
    Loading from cache

  - Installing magento/framework (100.0.2)
```
...
```
sjparkinson/static-review suggests installing sensiolabs/security-checker (Required for ComposerSecurityReview.)
lusitanian/oauth suggests installing symfony/http-foundation (Allows using the Symfony Session storage backend.)
lusitanian/oauth suggests installing predis/predis (Allows using the Redis storage backend.)
Writing lock file
Generating autoload files


                                                                                                                     
  [ErrorException]                                                                                                   
  file_get_contents(app/etc/NonComposerComponentRegistration.php): failed to open stream: No such file or directory  
                                                                                                                     


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...


mattjohnson $ 
```

**Comment by ihor-sviziev** [comment] 2015-11-23 18:09
:+1: have same issue during installation magento 2 to docker container https://github.com/mageinferno/magento2-docker-compose

**Comment by buskamuza** [comment] 2015-11-24 00:12
Looks like it's caused by recent changes in Composer.
`app/etc/NonComposerComponentRegistration.php` is mentioned in the root `composer.json` autoload section. But the file itself is copied from `magento/magento2-base` package by installer plugin.
Looks like, Composer generates autoload before running plugins. Probably, before it was not an issue that the file did not exist at the moment of autoload generation (or autoload generation was done on a later stage). So no error happened before. Now composer tries to read the file during autoload generation and can't do it.
We'll work on a fix for the latest versions of Composer.

**Comment by buskamuza** [comment] 2015-11-24 00:45
Internal ticket: MAGETWO-45957.

Temporary workaround: downgrade Composer to lower version. Verified with the following version:
```
composer self-update 1.0.0-alpha11
```

**Comment by markoshust** [comment] 2015-11-24 01:46
I can verify the composer downgrades resolves issue for now.

**Comment by kobid** [comment] 2015-11-24 04:40
working now thnks,

**Comment by Lewiscowles1986** [comment] 2015-11-24 09:56
this is not a solution as far as I am concerned, as magento2 main repo seems unaffected and it is only community edition that is affected for me

**Comment by comradesharf** [comment] 2015-11-24 10:30
Unfortunately downgrading composer doesn't work.
I have downgraded to 1.0.0-alpha11
```
  [ErrorException]                                                                                                   
  file_get_contents(app/etc/NonComposerComponentRegistration.php): failed to open stream: No such file or directory  

```

**Comment by daim2k5** [comment] 2015-11-24 10:37
I can also verify the composer downgrade resolves this issue for now.

**Comment by comradesharf** [comment] 2015-11-25 02:09
Running this won't work:
```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .
```
I have to clone the repository, downgrade my composer and run install.

**Comment by buskamuza** [comment] 2015-11-25 03:27
@comradesharf , did you try to run the original command with downgraded composer with `-vvv` option?
It would show some hint about the code that generates the error. Composer version `1.0.0-alpha` doesn't have the line, where it failed for the latest version.

**Comment by craigcarnell** [comment] 2015-11-25 11:14
I have the same issue with enterprise

**Comment by craigcarnell** [comment] 2015-11-25 11:32
Works for me after a downgrade

**Comment by davidalger** [comment] 2015-11-25 18:01
@mttjohnson The issue is reproducible in both CentOS and OS X with the latest version of composer:

> Composer version 1.0-dev (2b14f0a047dd4f3545ec82381f65c36ea93a4c81) 2015-11-25 17:13:09

Older versions work for me inside and out of our VMs. 

@buskamuza The following is the error with the -vvv to provide a trace:

```
Writing lock file
Generating autoload files


                                                                                                                     
  [ErrorException]                                                                                                   
  file_get_contents(app/etc/NonComposerComponentRegistration.php): failed to open stream: No such file or directory  
                                                                                                                     


Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:763
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 file_get_contents() at phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:763
 Composer\Autoload\AutoloadGenerator->getFileIdentifier() at phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:746
 Composer\Autoload\AutoloadGenerator->parseAutoloadsType() at phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:380
 Composer\Autoload\AutoloadGenerator->parseAutoloads() at phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:142
 Composer\Autoload\AutoloadGenerator->dump() at phar:///usr/local/bin/composer/src/Composer/Installer.php:344
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:134
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:167
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:98
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

```

The "extra/map" node is supposed to tell the magento-composer-installer to copy `app/etc/NonComposerComponentRegistration.php` and other stuff into the install location. This (broken) version of composer and/or magento-compser-installer is not copying _any_ of the stuff listed in the "extra/map" portion of the composer.json in the magento/magento2-base package.

**Comment by davidalger** [comment] 2015-11-25 18:04
@buskamuza One more note… the install seems to work with the following (fairly new) version:

> Composer version 1.0-dev (30e6a63958652e12d01bd3edbc7c7cd7500dde95) 2015-11-17 15:29:08

but breaks going put to the version released today:

> Composer version 1.0-dev (2b14f0a047dd4f3545ec82381f65c36ea93a4c81) 2015-11-25 17:13:09

So it's something between these two versions causing the problem.

**Comment by maksek** [comment] 2015-11-25 18:05
Seems like it is recent changes by composer. Can you downgrade it to alpha10 and try again?

**Comment by buskamuza** [comment] 2015-11-25 18:15
Thanks, @davidalger .
Yes, this is trace for one of non-working versions. I was surprised that @comradesharf has same issue on the older version. So I was wondering what part of code causes it.
`file_get_contents()` was not used for the autoload file in older versions, so this error should not happen.

The breaking change was introduced just few days ago. I propose to downgrade to `1.0.0-alpha11` just because this is latest version you can downgrade to. Though there may be newer commit in the branch.

**Comment by davidalger** [comment] 2015-11-25 18:31
I've narrowed the break down to this commit in composer: composer/composer@9710b26

**Comment by davidalger** [comment] 2015-11-25 18:33
@buskamuza Yes, we're downgrading here to workaround the issue, but I just wanted to provide as many details as I can so it can hopefully be solved in the mainline of composer sooner than later. :_

**Comment by xcomSteveJohnson** [comment] 2015-11-25 19:05
@davidalger Thanks; I verified the Composer downgrade solution also. Will push it today as troubleshooting and provide the link here.

**Comment by xcomSteveJohnson** [comment] 2015-11-25 19:57
[Composer troubleshooting topic](http://devdocs.magento.com/guides/v2.0/install-gde/trouble/tshoot_composer-fail.html). This is linked to from elsewhere in the Install Guide.

If it's incorrect, please reply here or on devdocs and I'll fix it ASAP.

**Comment by davidalger** [comment] 2015-11-26 18:23
This has been fixed in composer/composer#8072448cf3 and the issue no longer occurs with the latest dev snapshot.

**Comment by mazhalai** [comment] 2015-12-07 17:11
Closing since this has been fixed in composer.

**Closed by mazhalai** 2015-12-07 17:11 UTC

**Comment by markoshust** [comment] 2015-12-07 17:25
To prevent something like this happening again, is there a recommended way to specify a specific version of composer when installing? If this would randomly happen in the future, it would take down automated builds and cause a ton of headaches.

**Comment by davidalger** [comment] 2015-12-07 17:28
You could install composer from one of the versioned downloads here: https://getcomposer.org/download/ <https://getcomposer.org/download/> and just not use the latest snapshot (aka development nightly) on boxes running these automated builds.

--
David Alger
Director of Technology, Classy Llama
